name: Qujax Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Build and publish docs
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Upgrade pip and install wheel
      run: pip install --upgrade pip wheel
    - name: Install qujax
      run: |        
        pip install .
    - name: Install docs dependencies
      run: |
        pip install -r .github/workflows/docs/requirements.txt
    - name: Build docs
      timeout-minutes: 20
      run: |
        cd .github/workflows/docs        
        sphinx-build ../../../docs . -a
    - name: Upload docs as artefact
      uses: actions/upload-pages-artifact@v1
      with:
        path: .github/workflows/docs
